SageIntacct API:Fyle App Cleanup - Rename, Refactor, Remove, Documentation #100
fylein/fyle-intacct-api pull request #104
Opened 2021-08-16 09:58 UTC by NileshPant1999

2021-09-07 04:31 UTC, ashwin1111 commented on apps/fyle/connector.py
> +    def __format_updated_at(self, updated_at):
Type please

2021-09-07 04:37 UTC, ashwin1111 requested changes

2021-09-07 04:37 UTC, ashwin1111 commented on apps/fyle/tasks.py
> +            updated = []
`updated_at`

2021-09-07 04:37 UTC, ashwin1111 commented on apps/fyle/views.py
> +class ExpenseAttributesView(generics.ListAPIView):
Do we need a post for this class?

2021-09-07 04:37 UTC, ashwin1111 commented on apps/fyle/views.py
> +            )
new line

2021-09-08 13:23 UTC, ashwin1111 commented on apps/fyle/views.py
> +class ExpenseAttributesView(generics.ListAPIView):
@NileshPant1999 this isn't fixed yet

2021-09-08 13:49 UTC, NileshPant1999 commented on apps/fyle/views.py
> +class ExpenseAttributesView(generics.ListAPIView):
yes we don't need it

2021-09-08 13:58 UTC, ashwin1111 approved these changes

2021-09-09 08:29 UTC, merged