Auto sync of projects and chart of accounts
fylein/fyle-intacct-api pull request #229
Opened 2023-01-23 14:41 UTC by labhvam5

2023-01-24 10:19 UTC, Shwetabhk requested changes

2023-01-24 10:19 UTC, Shwetabhk commented on apps/sage_intacct/utils.py
> +        destination_attributes = DestinationAttribute.objects.filter(workspace_id=self.workspace_id,\
We don't need `\` for function params, you can just change the line and indent correctly

2023-01-24 10:19 UTC, Shwetabhk commented on apps/sage_intacct/utils.py
> +        #For setting active to False
```suggestion
        # For setting active to False
```

2023-01-24 10:19 UTC, Shwetabhk commented on apps/sage_intacct/utils.py
> +        for destination_id in disabled_fields_map:
I think deletion is not handled, what if the account is deleted from Sage Intacct?

2023-01-24 10:19 UTC, Shwetabhk commented on apps/sage_intacct/utils.py
> +        for destination_id in disabled_fields_map:
This will only disable the ones which are in the `disabled_field_maps`

What about the ones which are not returned at all by the API? Have we confirmed that that can't be a case?

2023-01-24 10:19 UTC, Shwetabhk commented on apps/sage_intacct/utils.py
> +        destination_attributes = DestinationAttribute.objects.filter(workspace_id=self.workspace_id,\
Same comments as above for this function

2023-01-24 10:19 UTC, Shwetabhk commented on apps/sage_intacct/utils.py
> +            destination_attributes = DestinationAttribute.objects.filter(workspace_id=self.workspace_id,\
Same comments as top function

2023-01-24 10:19 UTC, Shwetabhk commented on apps/sage_intacct/utils.py
> +            #For setting active to False
```suggestion
            # For setting active to False
```

2023-02-02 05:44 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +            fyle_payload: List[Dict] = create_fyle_categories_payload(categories=[], category_map={}, updated_categories=expense_attributes, destination_type=reimbursable_destination_type)
can pass fyle credentials in this to save one extra query

2023-02-02 07:27 UTC, labhvam5 commented on apps/mappings/tasks.py
> +            fyle_payload: List[Dict] = create_fyle_categories_payload(categories=[], category_map={}, updated_categories=expense_attributes, destination_type=reimbursable_destination_type)
We dont use `FyleCredentials` in the `create_fyle_categories_payload` function .

2023-02-02 07:41 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +            fyle_payload: List[Dict] = create_fyle_categories_payload(categories=[], category_map={}, updated_categories=expense_attributes, destination_type=reimbursable_destination_type)
ohh sorry i mean in upload_categories to fyle function

2023-02-02 14:09 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +    else:
move line 103 to this block

2023-02-02 14:09 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +        for destination_attribute in destination_attributes:
most of the logic seems to be same, please separate out as common function for disabling operation

2023-02-02 14:09 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +                    'detail': disabled_fields_map[destination_id]['detail']
sync_customers is not handled

2023-02-03 10:12 UTC, labhvam5 commented on apps/sage_intacct/utils.py
> +        for destination_attribute in destination_attributes:
will do it during rewrite can skip for now.

2023-02-03 10:13 UTC, labhvam5 commented on apps/sage_intacct/utils.py
> +                    'detail': disabled_fields_map[destination_id]['detail']
We dont need to add it for `customers` we are only disabling in case of `Project <> Project` mappings.

2023-02-03 10:17 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +                    'detail': disabled_fields_map[destination_id]['detail']
arey customer is also Project, check attribute type

2023-02-03 10:18 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +                    'detail': disabled_fields_map[destination_id]['detail']
replied to other comment

2023-02-06 14:37 UTC, ashwin1111 approved these changes

2023-02-07 05:21 UTC, Shwetabhk approved these changes

2023-02-07 05:23 UTC, merged