export item to sage intacct
fylein/fyle-intacct-api pull request #284
Opened 2023-05-16 04:38 UTC by DhaaraniCIT

2023-05-17 10:51 UTC, ashwin1111 approved these changes

2023-05-17 10:51 UTC, ashwin1111 commented on apps/sage_intacct/models.py
>          project_setting: MappingSetting = MappingSetting.objects.filter(
this is not needed now

2023-05-18 09:57 UTC, ashwin1111 requested changes

2023-05-18 09:57 UTC, ashwin1111 commented on apps/sage_intacct/models.py
> +            lineitem = lineitem.__dict__
why are we doing this? we're doing it anywhere

2023-05-18 09:57 UTC, ashwin1111 commented on apps/sage_intacct/models.py
> +                source_value = lineitem.vendor
this mapping cannot exist, you won't be able to map merchant / vendor to item in the 1st place

2023-05-18 09:57 UTC, ashwin1111 commented on apps/sage_intacct/models.py
> +                source_value = lineitem[attribute.display_name.replace(" ","_").lower()]
why all these hacks? can we follow what we do for other fields?

2023-05-18 09:57 UTC, ashwin1111 commented on apps/sage_intacct/models.py
> +        item_id = general_mappings.default_item_id if general_mappings.default_item_id else None
`general_mappings.default_item_id if general_mappings.default_item_id else None` this logic seems to be duplicated, do this at last when you don't have an item id

2023-05-18 10:00 UTC, DhaaraniCIT commented on apps/sage_intacct/models.py
> +                source_value = lineitem.vendor
we can, i saw option of merchant while creating expense field

2023-05-18 14:25 UTC, ashwin1111 approved these changes

2023-05-24 08:09 UTC, merged