Sync dimensions
fylein/fyle-intacct-api pull request #67
Opened 2021-04-22 10:53 UTC by NileshPant1999

2021-04-22 13:36 UTC, ashwin1111 requested changes

2021-04-22 13:36 UTC, ashwin1111 commented on apps/fyle/views.py
> +            )
new line

2021-04-22 13:36 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +    def sync_dimensions(self, workspace_id: str):
why is workspace id needed?

2021-04-22 13:36 UTC, ashwin1111 commented on apps/sage_intacct/views.py
> +                sage_intacct_connecter.sync_dimensions(kwargs['workspace_id'])
why is workspace id needed?

2021-04-22 13:39 UTC, NileshPant1999 commented on apps/sage_intacct/utils.py
> +    def sync_dimensions(self, workspace_id: str):
we need to pass it while syncing vendors and accounts

2021-04-22 13:40 UTC, NileshPant1999 commented on apps/sage_intacct/views.py
> +                sage_intacct_connecter.sync_dimensions(kwargs['workspace_id'])
needed while syncing vendor and accounts

2021-04-26 13:17 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +
remove workspace_id in function args, it's not needed now

2021-04-26 13:17 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> -            if general_settings and general_settings.corporate_credit_card_expenses_object == 'BILL':
remove workspace_id in function args, it's not needed now

2021-04-26 13:18 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +    def sync_dimensions(self, workspace_id: str):
not needed now

2021-04-26 13:18 UTC, ashwin1111 commented on apps/sage_intacct/views.py
> +                sage_intacct_connecter.sync_dimensions(kwargs['workspace_id'])
not needed

2021-04-26 13:18 UTC, ashwin1111 commented on apps/sage_intacct/views.py
> +            sage_intacct_connecter.sync_dimensions(kwargs['workspace_id'])
workspace_id not neeed

2021-04-27 12:02 UTC, ashwin1111 commented on apps/sage_intacct/views.py
> +                sage_intacct_connecter = SageIntacctConnector(sage_intacct_credentials, workspace_id=kwargs['workspace_id'])
sage_intacct_connector

2021-04-27 12:03 UTC, ashwin1111 commented on apps/sage_intacct/views.py
> +            sage_intacct_connecter = SageIntacctConnector(sage_intacct_credentials, workspace_id=kwargs['workspace_id'])
sage_intacct_connector

2021-04-27 12:03 UTC, ashwin1111 approved these changes

2021-04-27 12:58 UTC, Sravanksk commented on apps/mappings/tasks.py
> +
remove this extra tab space

2021-04-27 12:59 UTC, Sravanksk approved these changes

2021-04-27 15:34 UTC, merged