optimize bulk update/insert
fylein/fyle-intacct-api pull request #68
Opened 2021-04-22 10:53 UTC by NileshPant1999

2021-04-22 10:54 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +        Mapping.bulk_create_mappings(fyle_categories, 'PROJECT', 'PROJECT', workspace_id)
si_projects

2021-04-22 11:00 UTC, NileshPant1999 commented on apps/fyle/utils.py
> +            raise NotFoundClientError('Client ID dosen\'t exist', response.text)
```suggestion
            raise NotFoundClientError('Client ID doesn\'t exist', response.text)
```

2021-04-22 11:02 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +        Mapping.bulk_create_mappings(fyle_categories, 'PROJECT', 'PROJECT', workspace_id)
```suggestion
        Mapping.bulk_create_mappings(si_projects, 'PROJECT', 'PROJECT', workspace_id)
```

2021-04-22 13:32 UTC, ashwin1111 requested changes

2021-04-22 13:32 UTC, ashwin1111 commented on apps/fyle/utils.py
> +            project_attributes, "PROJECT", self.workspace_id)
'PROJECT'

2021-04-22 13:32 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +            "bank_account": [],
'account'

2021-04-22 13:32 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +            "credit_card_account": []
'ccc_account'

2021-04-22 13:32 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +            account_attributes['bank_account'].append({
same as above

2021-04-22 13:32 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +                account_attributes['credit_card_account'].append({
same as above

2021-04-22 13:32 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +            project_attributes, 'PROJECTS', self.workspace_id, True)
'PROJECT'

2021-04-22 13:32 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +        account_attributes = DestinationAttribute.bulk_create_or_update_destination_attributes(
no use in storing them in a variable

2021-04-22 13:32 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +        account_attributes = DestinationAttribute.bulk_create_or_update_destination_attributes(
also, we are appending `CHARGE_CARD_NUMBER` as well, current approach doesn't work

2021-04-22 13:32 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +        created_vendor = DestinationAttribute.bulk_create_or_update_destination_attributes({
Shouldn't this be `create_or_update_destination_attributes`?

2021-04-22 13:46 UTC, NileshPant1999 commented on apps/sage_intacct/utils.py
> +        account_attributes = DestinationAttribute.bulk_create_or_update_destination_attributes(
ohh yes i didn't see that will update the logic

2021-04-22 13:47 UTC, NileshPant1999 commented on apps/sage_intacct/utils.py
> +        created_vendor = DestinationAttribute.bulk_create_or_update_destination_attributes({
sorry i forget to push the latest changes.

2021-05-03 09:21 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +        si_projects = upload_projects_to_fyle(workspace_id=workspace_id)
upload_projects_to_fyle(workspace_id)

2021-05-03 09:22 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +    if general_settings.auto_map_employees and general_settings.corporate_credit_card_expenses_object=='CHARGE_CARD_TRANSACTION':
```general_settings.corporate_credit_card_expenses_object == 'CHARGE_CARD_TRANSACTION'```

2021-05-03 09:22 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +
rm

2021-05-03 09:23 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +            "account": [],
'account'

2021-05-03 09:23 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +            "ccc_account": []
'ccc_account'

2021-05-03 09:32 UTC, ashwin1111 approved these changes

2021-05-03 16:55 UTC, Sravanksk approved these changes

2021-05-04 10:25 UTC, ashwin1111 requested changes

2021-05-04 10:25 UTC, ashwin1111 commented on requirements.txt
> +fyle_accounting_mappings==0.16.6
set it to `0.15.0`

2021-05-04 10:34 UTC, merged