store cluster domain in workspace_table
fylein/fyle-intacct-api pull request #89
Opened 2021-06-28 17:17 UTC by NileshPant1999

2021-06-30 05:57 UTC, ashwin1111 requested changes

2021-06-30 05:57 UTC, ashwin1111 commented on apps/workspaces/views.py
> +            cluster_domain = fyle_connector.get_cluster_domain()['cluster_domain']
Please check app as well, we have a /cluster_domain api which returns it. You'll have to take care of all that. Basically only 1 call per workspace at time of creation should go to fyle. Rest should read from table.

2021-06-30 05:59 UTC, NileshPant1999 commented on apps/workspaces/views.py
> +            cluster_domain = fyle_connector.get_cluster_domain()['cluster_domain']
okay will take care of this.

2021-06-30 13:15 UTC, ashwin1111 approved these changes

2021-06-30 13:15 UTC, ashwin1111 commented
TODO: Have scripts ready before deploy

2021-07-06 11:07 UTC, Sravanksk approved these changes

2021-07-14 14:59 UTC, ashwin1111 requested changes

2021-07-14 14:59 UTC, ashwin1111 commented on apps/sage_intacct/utils.py
> +        cluster_domain = workspace.cluster_domain
sir, this approach would break for existing clients

2021-07-15 09:24 UTC, Shwetabhk commented on apps/sage_intacct/utils.py
> +        cluster_domain = workspace.cluster_domain
```python
if not cluster_domain:
   fyle_credentials = FyleCredential.objects.get(workspace_id=self.workspace_id)
   fyle_connector = FyleConnector(fyle_credentials.refresh_token, self.workspace_id)
   cluster_domain = fyle_connector.get_cluster_domain()
   workspace.cluster_domain = cluster_domain
   workspace.save()
```

2021-07-15 11:59 UTC, merged