Fyle 3qe1ap
fylein/fyle-intacct-api pull request #95
Opened 2021-07-06 05:14 UTC by NileshPant1999

2021-07-13 11:08 UTC, Sravanksk commented on apps/fyle/utils.py
> +                self.workspace_id,
add this flag `update=True`

2021-07-13 11:09 UTC, Sravanksk commented on apps/mappings/signals.py
> +from django_q.models import Schedule
remove unused imports

2021-07-13 11:10 UTC, Sravanksk commented on apps/mappings/signals.py
> +def run_porun_pre_mapping_settings_triggersst_save(sender, instance: MappingSetting, **kwargs):
`run_pre_mapping_settings_triggers`

2021-07-13 11:10 UTC, Sravanksk commented on apps/mappings/signals.py
> +    instance.source_field = instance.source_field .upper().replace(' ', '_')
`instance.source_field.upper().replace(' ', '_')`

2021-07-13 11:23 UTC, Sravanksk commented on apps/mappings/tasks.py
> +        for si_attribute in sageintacct_attributes:
remove this, we are already doing the same operation in 410

2021-07-13 11:25 UTC, Sravanksk commented on apps/mappings/tasks.py
> +def upload_attributes_to_fyle(workspace_id: int, sageintacct_attribute_type: str, fyle_attribute_type: str):
check latest changes in netsuite-api and fix this function

2021-07-13 11:26 UTC, Sravanksk commented on apps/mappings/utils.py
> +                'use_intacct_employee_locations': general_mapping['use_intacct_employee_locations'],
remove `,`

2021-07-13 11:27 UTC, Sravanksk commented on apps/mappings/views.py
> +from django_q.models import Schedule
remove unused imports

2021-07-13 11:27 UTC, Sravanksk commented on apps/sage_intacct/urls.py
> +    RefreshSageIntacctDimensionView, ExpenseCustomFieldsView,SageIntacctAttributesCountView
add space   `RefreshSageIntacctDimensionView, ExpenseCustomFieldsView, SageIntacctAttributesCountView`

2021-07-13 11:41 UTC, Sravanksk requested changes
..

2021-07-13 11:50 UTC, Sravanksk commented on apps/fyle/utils.py
> +                    'source_id': 'expense_custom_field.{}.{}'.format(custom_field['name'].lower(), count),
remove dupes, check this for ref 
https://github.com/fylein/fyle-netsuite-api/commit/2b7b80c14b9333e84d01277015412fe5f531ce41

2021-07-14 09:31 UTC, Sravanksk commented on apps/fyle/views.py
> +            {'attribute_type': 'COST_CENTER', 'display_name': 'COST Center'},
`{'attribute_type': 'COST_CENTER', 'display_name': 'Cost Center'},`

2021-07-14 09:32 UTC, Sravanksk commented on apps/mappings/signals.py
> +
remove extra lines

2021-07-14 09:33 UTC, Sravanksk commented on apps/mappings/tasks.py
> +            general_settings.corporate_credit_card_expenses_object == 'CHARGE_CARD_TRANSACTION':
fix indentation

2021-07-14 09:33 UTC, Sravanksk commented on apps/mappings/tasks.py
> +
rm extra line

2021-07-14 09:35 UTC, Sravanksk commented on apps/mappings/tasks.py
> +
remove extra line

2021-07-14 09:36 UTC, Sravanksk commented on apps/mappings/utils.py
> -
why removing this line ?

2021-07-14 09:36 UTC, Sravanksk commented on apps/mappings/views.py
> +from fyle_accounting_mappings.serializers import MappingSettingSerializer
remove these unused imports

2021-07-14 09:37 UTC, Sravanksk commented on apps/mappings/views.py
> +from .tasks import schedule_fyle_attributes_creation, upload_attributes_to_fyle, schedule_cost_centers_creation
unused import

2021-07-14 09:38 UTC, Sravanksk requested changes
@NileshPant1999 added few minor comments

2021-07-16 05:00 UTC, Sravanksk approved these changes

2021-07-19 10:55 UTC, ashwin1111 commented on apps/fyle/models.py
> +                    'custom_properties': expense_custom_properties if expense_custom_properties else {}
make sure to run the script post deploy, also please take care of running this on staging once deployed

2021-07-19 10:55 UTC, ashwin1111 commented on apps/mappings/constants.py
> +]
new line

2021-07-19 10:57 UTC, ashwin1111 commented on apps/mappings/signals.py
> +    if instance.is_custom:
if elif else, reply here incase if it breaks the flow

2021-07-19 10:58 UTC, ashwin1111 commented on apps/mappings/signals.py
> +        :param sender: Sender Class
indent

2021-07-19 10:58 UTC, ashwin1111 commented on apps/mappings/signals.py
> +    [default_attributes.append(attribute['attribute_type']) for attribute in attributes]
Sravan has changed something around this, please check latest version

2021-07-19 11:00 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +        sync_sageintacct_attribute(mapping_setting.destination_field, workspace_id)
sync_sage_intacct_attributes

2021-07-19 11:01 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +        sage_intacct_connection.sync_projects()
checkout if we are syncing customer too

2021-07-19 11:02 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +        sage_intacct_connection.sync_dimensions()
please remove this off, heavy not needed operation

2021-07-19 11:02 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +        sage_intacct_connection.sync_projects()
checkout if we are syncing customer too

2021-07-19 11:03 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +def auto_create_cost_center_mappings(workspace_id):
type

2021-07-19 11:04 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +            fyle_connection.sync_cost_centers(active_only=True)
You have removed the active_only  flag above, please check and remove

2021-07-19 11:05 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +        fyle_connection.sync_cost_centers(active_only=True)
Why sync it twice? we are already doing in `sync_sageintacct_attribute`

2021-07-19 11:07 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +    if mapping_settings:
this is not required, check and remove

2021-07-19 11:07 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +        schedule, _=Schedule.objects.get_or_create(
`schedule, _= Schedule.objects.get_or_create(`

2021-07-19 11:08 UTC, ashwin1111 commented on apps/sage_intacct/views.py
> +        return ExpenseReport.objects.filter(expense_group__workspace_id=self.kwargs['workspace_id']) \
space would break the query no?

2021-07-19 11:08 UTC, ashwin1111 commented on apps/sage_intacct/views.py
> +        return Bill.objects.filter(expense_group__workspace_id=self.kwargs['workspace_id']) \
space would break the query no?

2021-07-19 11:08 UTC, ashwin1111 commented on apps/sage_intacct/views.py
> +        return ChargeCardTransaction.objects.filter(expense_group__workspace_id=self.kwargs['workspace_id']) \
space would break the query no?

2021-07-19 11:10 UTC, ashwin1111 commented on scripts/009-move-import-projects-flag.sql
> +where source_field = 'PROJECT' and workspace_id in (select workspace_id from configurations where import_projects = 't');
sir there is no configurations table in Intacct :P

2021-07-19 14:09 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +        sage_intacct_connection.sync_projects()
no we are not syncing customers

2021-07-19 14:34 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +        fyle_connection.sync_cost_centers(active_only=True)
we are not syncing cost center inside sync_sage_intacct_attribute

2021-07-19 14:45 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +    if mapping_settings:
no it is there but there was a minor change
`if mapping_settings:
        for mapping_setting in mapping_settings:
            if mapping_setting.import_to_fyle:
                sync_netsuite_attribute(mapping_setting.destination_field, workspace_id)
                auto_create_expense_fields_mappings(
                    workspace_id, mapping_setting.destination_field, mapping_setting.source_field
                )
`

2021-07-19 14:55 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +        fyle_connection.sync_cost_centers(active_only=True)
got it, this is fyle dimension. Take care of the flag, I remember it was removed above.

2021-07-19 19:26 UTC, NileshPant1999 commented on apps/sage_intacct/views.py
> +        return ExpenseReport.objects.filter(expense_group__workspace_id=self.kwargs['workspace_id']) \
pycharm did it automatically I think so it will not break i think any removing it just for consistency.

2021-07-19 19:26 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +    if mapping_settings:
it is there in netsuite

2021-07-20 05:17 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +    if mapping_settings:
This doesn't add any value, the query returns [] if there aren't any results. For loop doesn't iterate over them.

2021-07-20 05:18 UTC, ashwin1111 commented on apps/mappings/signals.py
> +    if instance.is_custom:
this isn't resolved yet

2021-07-20 05:19 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +        sage_intacct_connection.sync_classifications()
We don't have classes in Sage Intacct

2021-07-20 05:21 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +def sync_sage_intacct_attributes(sageintacct_attribute_type: str, workspace_id: int):
handle user dimensions as well

2021-07-20 05:58 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +        sage_intacct_connection.sync_classifications()
yup sorry i forget

2021-07-20 10:25 UTC, NileshPant1999 commented on apps/mappings/signals.py
> +    if instance.is_custom:
Hey I am not sure about this can we leave it as it @ashwin1111

2021-07-20 10:42 UTC, NileshPant1999 commented on apps/mappings/signals.py
> +    if instance.is_custom:
will discuss with @Sravanksk separately and then will remove in every app

2021-07-20 10:45 UTC, ashwin1111 commented on apps/mappings/signals.py
> +    if instance.is_custom:
if elif elif shouldn't break any flow. Can leave it as it is, doesn't harm anything though.

2021-07-20 12:24 UTC, NileshPant1999 commented on apps/mappings/signals.py
> +    if instance.is_custom:
yes that would work i was afraid about the else you said

2021-07-22 08:07 UTC, merged